# Generated by Django 3.2.12 on 2022-04-12 13:39

import courses.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20220411_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='input_data',
            field=courses.fields.NonStrippingTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='code',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
