# Generated by Django 3.2.12 on 2022-04-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0006_auto_20220425_0129'),
        ('courses', '0008_auto_20220426_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='problem_to_solve',
            field=models.ManyToManyField(blank=True, to='problem.Problem'),
        ),
        migrations.AddField(
            model_name='file',
            name='problem_to_solve',
            field=models.ManyToManyField(blank=True, to='problem.Problem'),
        ),
        migrations.AddField(
            model_name='image',
            name='problem_to_solve',
            field=models.ManyToManyField(blank=True, to='problem.Problem'),
        ),
        migrations.AddField(
            model_name='text',
            name='problem_to_solve',
            field=models.ManyToManyField(blank=True, to='problem.Problem'),
        ),
        migrations.AddField(
            model_name='video',
            name='problem_to_solve',
            field=models.ManyToManyField(blank=True, to='problem.Problem'),
        ),
        migrations.AlterField(
            model_name='module',
            name='visible',
            field=models.BooleanField(default=False, verbose_name='Видимость обучающимся'),
        ),
    ]
