# Generated by Django 3.2.12 on 2022-05-02 15:38

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20220502_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='problem_to_solve',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Test'), (2, 'asdf')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='problem_to_solve',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Test'), (2, 'asdf')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='problem_to_solve',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Test'), (2, 'asdf')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='problem_to_solve',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Test'), (2, 'asdf')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='problem_to_solve',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Test'), (2, 'asdf')], max_length=3, null=True),
        ),
    ]
