# Generated by Django 3.2.12 on 2022-05-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0006_auto_20220425_0129'),
        ('courses', '0011_auto_20220502_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='problem_to_solve',
        ),
        migrations.AddField(
            model_name='code',
            name='problem_to_solve',
            field=models.ManyToManyField(blank=True, null=True, to='problem.Problem'),
        ),
        migrations.RemoveField(
            model_name='file',
            name='problem_to_solve',
        ),
        migrations.AddField(
            model_name='file',
            name='problem_to_solve',
            field=models.ManyToManyField(blank=True, null=True, to='problem.Problem'),
        ),
        migrations.RemoveField(
            model_name='image',
            name='problem_to_solve',
        ),
        migrations.AddField(
            model_name='image',
            name='problem_to_solve',
            field=models.ManyToManyField(blank=True, null=True, to='problem.Problem'),
        ),
        migrations.RemoveField(
            model_name='text',
            name='problem_to_solve',
        ),
        migrations.AddField(
            model_name='text',
            name='problem_to_solve',
            field=models.ManyToManyField(blank=True, null=True, to='problem.Problem'),
        ),
        migrations.RemoveField(
            model_name='video',
            name='problem_to_solve',
        ),
        migrations.AddField(
            model_name='video',
            name='problem_to_solve',
            field=models.ManyToManyField(blank=True, null=True, to='problem.Problem'),
        ),
    ]
