# Generated by Django 3.2.12 on 2022-05-02 17:26

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20220502_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='problem_to_solve',
        ),
        migrations.RemoveField(
            model_name='file',
            name='problem_to_solve',
        ),
        migrations.RemoveField(
            model_name='image',
            name='problem_to_solve',
        ),
        migrations.RemoveField(
            model_name='text',
            name='problem_to_solve',
        ),
        migrations.RemoveField(
            model_name='video',
            name='problem_to_solve',
        ),
        migrations.AddField(
            model_name='content',
            name='problem_to_solve',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Test'), (2, 'asdf'), (3, '3123')], max_length=3, null=True),
        ),
    ]
