# Generated by Django 3.2.12 on 2022-05-02 17:27

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20220502_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='problem_to_solve',
        ),
        migrations.RemoveField(
            model_name='content',
            name='visible',
        ),
        migrations.AddField(
            model_name='code',
            name='problem_to_solve',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Test'), (2, 'asdf'), (3, '3123')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='code',
            name='visible',
            field=models.BooleanField(default=False, verbose_name='Видимость контента'),
        ),
        migrations.AddField(
            model_name='file',
            name='problem_to_solve',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Test'), (2, 'asdf'), (3, '3123')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='visible',
            field=models.BooleanField(default=False, verbose_name='Видимость контента'),
        ),
        migrations.AddField(
            model_name='image',
            name='problem_to_solve',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Test'), (2, 'asdf'), (3, '3123')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='visible',
            field=models.BooleanField(default=False, verbose_name='Видимость контента'),
        ),
        migrations.AddField(
            model_name='text',
            name='problem_to_solve',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Test'), (2, 'asdf'), (3, '3123')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='visible',
            field=models.BooleanField(default=False, verbose_name='Видимость контента'),
        ),
        migrations.AddField(
            model_name='video',
            name='problem_to_solve',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Test'), (2, 'asdf'), (3, '3123')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='visible',
            field=models.BooleanField(default=False, verbose_name='Видимость контента'),
        ),
    ]
