# Generated by Django 3.2.12 on 2022-05-02 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0006_auto_20220425_0129'),
        ('courses', '0014_auto_20220502_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='problem_to_solve',
        ),
        migrations.RemoveField(
            model_name='file',
            name='problem_to_solve',
        ),
        migrations.RemoveField(
            model_name='image',
            name='problem_to_solve',
        ),
        migrations.RemoveField(
            model_name='text',
            name='problem_to_solve',
        ),
        migrations.RemoveField(
            model_name='video',
            name='problem_to_solve',
        ),
        migrations.AddField(
            model_name='code',
            name='problem_solve',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='problem.problem'),
        ),
        migrations.AddField(
            model_name='file',
            name='problem_solve',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='problem.problem'),
        ),
        migrations.AddField(
            model_name='image',
            name='problem_solve',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='problem.problem'),
        ),
        migrations.AddField(
            model_name='text',
            name='problem_solve',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='problem.problem'),
        ),
        migrations.AddField(
            model_name='video',
            name='problem_solve',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='problem.problem'),
        ),
    ]
