# Generated by Django 3.2.12 on 2022-04-18 11:56

import courses.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание задачи')),
                ('input_description', models.TextField(verbose_name='Входные данные')),
                ('output_description', models.TextField(verbose_name='Выходные данные')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('last_update_time', models.DateTimeField(auto_now_add=True, verbose_name='Обновлено')),
                ('time_limit', models.IntegerField(verbose_name='Ограничение по времени')),
                ('memory_limit', models.IntegerField(verbose_name='Ограничение по памяти')),
                ('visible', models.BooleanField(default=True, verbose_name='Открыта для всех')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Время попытки')),
                ('code', courses.fields.NonStrippingTextField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='problem.problem', verbose_name='Задача')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
