# Generated by Django 3.2.12 on 2022-04-19 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_submission_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='problem_tests_input',
            field=models.JSONField(default='no data'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='problem_tests_output',
            field=models.JSONField(default='no data'),
            preserve_default=False,
        ),
    ]
