# Generated by Django 3.2.12 on 2022-04-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0004_auto_20220420_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_tests_input',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_tests_output',
            field=models.JSONField(default={}),
        ),
    ]
