# Generated by Django 3.2.12 on 2022-05-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0006_auto_20220425_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='problem',
        ),
        migrations.AddField(
            model_name='submission',
            name='problem',
            field=models.ManyToManyField(related_name='submissions', to='problem.Problem', verbose_name='Задача'),
        ),
    ]
