# Generated by Django 3.2.12 on 2022-05-05 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0007_auto_20220506_0144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='problem',
        ),
        migrations.AddField(
            model_name='submission',
            name='problem',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='problem.problem', verbose_name='Задача'),
            preserve_default=False,
        ),
    ]
